### ISSUE TITLE
make QAing locations easy - claiming locations

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/vial#657]
as much as possible, we just want to implement the same QA system we have on reports for locations as well. (All of these are things that already exist for reports.)

Key pieces to implement first:
* add a "claimed" field to the location so users can add themselves as responsible for a location
* and a claimed time/date stamp field as well
* add a filter to the locations table page for Claimed w/ options All / Claimed by you / Claimed by anyone / unclaimed
* show "Is pending review" and "Claimed by" as columns in the locations table page between "request a call" and "full address"
* Add bulk action options "Claim locations" and "Unclaim locations you have claimed"

**Comment by simonw** [comment]
Re-opening this for any notes we may have while testing it in staging.

**Comment by ugotsoul** [comment]
Oops, I forgot to add the fields for reviewing locations notes in the admin view, like this for reports:

![image](https://user-images.githubusercontent.com/6485006/122479883-ac651000-cf80-11eb-809a-8d7ca8afdf25.png)

Will open another PR for this

**Comment by ugotsoul** [comment]
I think this is ready to be closed.

Documenting other things we did:

- Fix: @simonw created an Approved tag on production, this was causing an error creating a review note: https://github.com/CAVaccineInventory/vial/issues/690
- Added permissions for viewing review notes and tags for web bankers and staff (groups: WB trainee, Vial WB limited, Vaccinate CA staff)
- Added permissions to edit/create/delete notes and tags for Report QA role.
