### ISSUE TITLE
add county priority to VIAL

### ISSUE THREAD

**Issue by lisabettefay** [CAVaccineInventory/vial#662]
Since we are so focused on the priority counties (as determined by the [SVI index](https://docs.google.com/spreadsheets/d/1wzlYwxoQ-EQE9rKcHv1iwUBkWKDJV7v5Qf5OnLI9fA0/edit#gid=1009463255) ), I am hoping we can put those values (VTS Priority # or the SVI index # ) on the the county 'object' (did i say that right? the place where the other info about a county lives). That way we could sort/filter by that indicator with more ease and be able to work those counties in more efficient ways. At least that is my feeling.

Ideally, we would be able to see the priority # of a county both on the location record and some place on the report record.

Let me know if this needs clarifying or a better source.

Thank you!

**Comment by ugotsoul** [comment]
@lisabettefay sounds good - Does the VTS Priority number get updated or is it static?

**Comment by lisabettefay** [comment]
it is static.

**Comment by lisabettefay** [comment]
the expand on that it is an index determined by the CDC that references social vulnerability. the report is from 2018, but it is the latest and greatest resource for predicting vaccine barriers . it is used fairly commonly for this purpose in these pandemic days.

if you are interested: 
https://docs.google.com/spreadsheets/d/1wzlYwxoQ-EQE9rKcHv1iwUBkWKDJV7v5Qf5OnLI9fA0/edit#gid=1009463255
https://vaccineplanner.org/

one thing i will say is id like to do a final pass through to make sure the counties are in the proper order. there have been a few instances of missing counties or missing FIPS.

**Comment by ugotsoul** [comment]
While testing my code, I noticed that the spreadsheet has about 3136 counties but our database has 3233 counties. Why is that? @simonw @lisabettefay

**Comment by ugotsoul** [comment]
ok two notes from 

> While testing my code, I noticed that the spreadsheet has about 3136 counties but our database has 3233 counties. Why is that? @simonw @lisabettefay

From discussion with lisabette: "...Is that the CA counties might be already accounted for somehow. because they came first so the numbering is a little wonky." and "and secondly, our counties included puerto rico, and other territories that have fips numbers but are not on the SVI and there for are not ranked."

**Comment by ugotsoul** [comment]
The counties (97 total) that were not updated by the spreadsheet are in this gist:

https://gist.github.com/ugotsoul/cbd31dd049316637fd8667244a8c6781

**Comment by ugotsoul** [comment]
> The counties (97 total) that were not updated by the spreadsheet are in this gist:
> 
> https://gist.github.com/ugotsoul/cbd31dd049316637fd8667244a8c6781

I just checked the id's of one of my counties on local vs prod/staging and it seems like my local db has different ids? I'm going to try to revert my db to an clean state

**Comment by ugotsoul** [comment]
I rebuilt my db following the instructions in our readme and still have ids that don't map to the same counties locally, which makes it a bit hard to test locally.

**Comment by ugotsoul** [comment]
A cleaner csv to get vts_priorty numbers from (thanks lisabette!) https://docs.google.com/spreadsheets/d/1vFjVRD_m0URWlrgDJ5NG7RXPA-xYcG5vWRnCRN9_giE/edit#gid=0

**Comment by lisabettefay** [comment]
i hope that helps some!

**Comment by ugotsoul** [comment]
@simonw there are 3233 counties in vial but there are several more counties that have ids above 3233:


MARYLAND | MD | Baltimore City | 24510 | Baltimore city, Maryland | 0.8312 | 531 | 3234
-- | -- | -- | -- | -- | -- | -- | --
MISSOURI | MO | St. Louis City | 29510 | St. Louis city, Missouri | 0.7796 | 693 | 3235
VIRGINIA | VA | Fairfax City | 51600 | Fairfax city, Virginia | 0.2411 | 2384 | 3236
VIRGINIA | VA | Franklin City | 51620 | Franklin city, Virginia | 0.7175 | 888 | 3237
VIRGINIA | VA | Richmond City | 51760 | Richmond city, Virginia | 0.7729 | 714 | 3238
VIRGINIA | VA | Roanoke City | 51770 | Roanoke city, Virginia | 0.8038 | 617 | 3239

Why is that?

**Comment by simonw** [comment]
Those five counties were added in look like the counties from https://github.com/CAVaccineInventory/vial/issues/674#issuecomment-862786937 - they were renamed at some point because they had ambiguous names (e.g. Baltimore, MD v.s. Baltimore, MD where the second one was actually Baltimore City, MD).

**Comment by simonw** [comment]
Using the primary key for counties is likely to run into problems since that primary key is assigned on a first-come, first-served basis - and it's likely that counties will have been imported in different orders in different environments due to us spotting edge-cases like the above one.

Using the fips_code as the unique identifier for a county should be consistent across different environments.

**Comment by ugotsoul** [comment]
Thanks for the context! And I'll change my code to use `fips_code`

**Comment by ugotsoul** [comment]
I imported  vts priorty for 3142 counties to staging and production today.
