### ISSUE TITLE
Tweaks to presentation for fields in the Location view

### ISSUE THREAD

**Issue by rhkeeler** [CAVaccineInventory/vial#670]
Bold the following field names:
* Name
* Location Type
* Phone Number
* Full Address
* State
* County
* Latitude
* Longitude

Add helptext to the following fields:
* County - "Use the 🔍 lookup tool or enter the county number."
* Longitude - "Enter coordinates up to 5 decimal places, or use search box and pin below to ‘pin’ the location"
* Hours - "Do not enter hours here for mobile clinics! File a report and put mobile clinic hours in the public notes."
* Provider - "If you're certain that this location is part of a chain or network of providers -- like CVS, Costco, or Kroger -- add the right provider network."

and, hide the Restrictions text field.

**Comment by rhkeeler** [comment]
I think we do still get data into those fields sometimes, so I'd like to keep showing them in case? But they could be hidden behind a collapsed section if that would help WBers.

**Comment by lisabettefay** [comment]
> I think we do still get data into those fields sometimes, so I'd like to keep showing them in case? But they could be hidden behind a collapsed section if that would help WBers.

I think it would, so if it is not a lot of work, I think it would make us faster at web banking. (adding locations and QAing those locations)

**Comment by ugotsoul** [comment]
> I think we do still get data into those fields sometimes, so I'd like to keep showing them in case? But they could be hidden behind a collapsed section if that would help WBers.

I'll put this under the collapsed field `"Location data for debugging"`

**Comment by ugotsoul** [comment]
@rhkeeler there's no restrictions field on a location model, did you mean on reports?

**Comment by lisabettefay** [comment]
> @rhkeeler there's no restrictions field on a location model, did you mean on reports? reports has a `restriction_notes` fields

you are correct. currently, i am only aware of the restrictions field on the report.

**Comment by ugotsoul** [comment]
FYI many of these fields are required to save a model, so they are automatically bolded (including state, which is now under a collapsed header) @rhkeeler 

The fields that need to be bolded, that are not required are: 
- Phone #
- County 
- Full Address

**Comment by lisabettefay** [comment]
> FYI many of these fields are required to save a model, so they are automatically bolded (including state, which is now under a collapsed header)

Is state being hidden? Web bankers are trained that it needs to be added in order for a loc report to submit?

**Comment by ugotsoul** [comment]
Oops sorry you meant city not state! I'll change that.
